var V3XOfficeLang = {
	menu_name:"菜单名称",
	menu_OpenFile:"打开文件",
	menu_SaveFile:"保存文件",
	menu_PageSet:"页面设置",
	menu_Print:"打印",
	menu_PrintPreview:"打印预览",
	menu_SaveExit:"返回",
	menu_A8Col:"协同",
	menu_TopVer:"高级版本",
	menu_CharPostil:"文字批注",
	menu_HandWritePostil:"手写批注",
	menu_ResetPostil:"重新批注",
	menu_ClearTrail:"文档清稿",
	menu_DisplayTrail:"显示痕迹",
	menu_HiddenTrail:"隐藏痕迹",
	menu_SginSeal:"加签印章",
	menu_CheckSeal:"印章校验",
	menu_BrowseChar:"浏览文字",
	menu_BrowseHandWrite:"浏览手写",
	menu_A8Other:"其它",
	menu_FullScreenMode:"全屏模式",
	menu_OcxVer:"控件版本",
	menu_Offcie_CoalitionDoc:"合并文档(&D)...",
	menu_Offcie_ProtectDoc:"保护文档(&P)...",
	menu_Offcie_Macro:"宏(&M)",
	menu_Offcie_Option:"选项(&O)...",
	menu_Offcie_BookMark:"书签(&K)...",
	menu_CurrentVer:"当前版本",
	menu_Ver1:"花脸一",
	menu_Ver2:"花脸二",
	menu_Ver3:"花脸三",
	menu_Ver4:"花脸四",
	menu_Ver5:"花脸五",
	menu_BarCode:"加盖二维码",
	menu_EditContent:"修改正文",
	menu_RepairContent:"修复正文",
	
	alert_err_HandWrite_Disbaled:"Office控件不可用！",
	alert_err_UpdateOcx:"office控件装载文件失败",
	alert_err_OcxVer:"客户端控件版本与服务器端不一致,请到登陆页面'辅助程序安装'更新office控件",
	alert_err_taohong:"套红错误，不能保存，请重新打开操作",
	alert_err_OcxFileBig:"内容太大，最大允许{0}",
	alert_err_OcxFileBig_not_open:"当前正文内容太大，控件最大允许打开文件大小为{0}K,建议下载查看。",
	alert_ClearDoc:"手写批注后,文字不可以修改,修改文字请进行清稿",
	alert_restTrail:"手写批注为文档备份,进行手写批注请点击重新批注",
	alert_Ocx:"控件",
	alert_SignNoEffect:"盖章后又对文字进行了修改,盖章无效,请重新盖章",
	alert_NotEdit:"用户{0}正在编辑此文件，不能修改！",
	alert_NotHandwrite:"用户{0}正在文单签批，请稍后操作！",
	alert_CurrectVerNoEdit:"当前版本不可以修改",
	alert_SignNotEdic:"已经盖章，不允许修改！",
	alert_NotSign:"盖章只能在‘文字批注’时使用，当前编辑模式为‘手写批注’，无法进行盖章！",
	alert_SaveFalseNotChange:"当前文档保存失败!无法切换版本",
	alert_saveEdit:"是否保存当前修改?",
	alert_signature_isselected:"当前正文中可能有印章处于选中状态，请取消选中状态，再做其他操作！",
	alert_cancelClearDocument:"取消清稿吗?",
	alert_lostContent:"文档修改,清稿将丢失刚修改内容,是否继续?",
	alert_noHandWriteLocation:"不能进行文单签批,没有设置签批的位置",
	alert_convertToPdfInvalidArgument:"当前文档转化为PDF文档的时候，传入的参数不合法，请重新设置参数",
	alert_pleaseInstallAdobePDF : "使用WORD转PDF的功能，请先安装PDF虚拟打印机。",
	alert_saveFaile : "保存正文失败，请检查日志，查找原因。",
	alert_err_OcxSave : "保存正文失败,服务器返回信息:{0}",
	alert_info_canNotSign:"该文档中有专业签章，不能再盖图片章！",
	detail_info_9001 : "<li></li>",
	detail_info_9002 : "<li></li>",
	office_qitaliulanqi: "当前浏览器不支持Office正文，请您使用IE浏览器",
	alert_subject_haveSpecSign:"流程标题中含有office文件名不支持的特殊字符，因此将采用ID形式！",
	alert_YozoModifyWps:"本地安装的是永中Office，不支持对wps正文的编辑，系统自动将正文置为只读状态!",
	alert_YozoSaveWps:"本地安装的是永中Office软件，不能保存wps正文，请安装WPS或者微软Office来操作！",
	alert_low_OcxVer:"客户端控件版本较低打开文件很慢,请到登陆页面'辅助程序安装'更新office控件!",
	alert_repairContent:"修复模式下系统默认当前正文已经损坏,将尝试用备份文件来进行修复正文,过程中可能会存在数据丢失,请慎用！提交流程生效,确认要继续吗？",
	alert_info_canNotRepairContent:"该文档中有签章,不能进行文档修复!",
	alert_NoAdvance_office:"只有高级office套件才具备此功能,请检查对应插件是否授权,或授权文件设置是否正确!"
}